### ISSUE TITLE
[BUG]  http request /console/api/setup 404 not found

### ISSUE THREAD

**Issue by zhy1** [BorisPolonsky/dify-helm#122]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
% kubectl get po -n dify
NAME                            READY   STATUS    RESTARTS   AGE
dify-api-6fccb5595c-6ttlf       1/1     Running   0          4m14s
dify-postgresql-primary-0       1/1     Running   0          17m
dify-postgresql-read-0          1/1     Running   0          17m
dify-proxy-659d649bf9-wv85b     1/1     Running   0          2m8s
dify-redis-master-0             1/1     Running   0          17m
dify-redis-replicas-0           1/1     Running   0          17m
dify-redis-replicas-1           1/1     Running   0          16m
dify-redis-replicas-2           1/1     Running   0          15m
dify-sandbox-544c9cfdb7-rvsf4   1/1     Running   0          17m
dify-web-c6bc76c9c-22p8l        1/1     Running   0          17m
dify-worker-dbd49554b-lskbh     1/1     Running   0          17m
weaviate-0                      1/1     Running   0          17m

% kubectl get svc -n dify
NAME                         TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)    AGE
dify                         ClusterIP   192.168.248.213   <none>        80/TCP     3m15s
dify-api                     ClusterIP   192.168.249.173   <none>        5001/TCP   3m15s
dify-postgresql-primary      ClusterIP   192.168.143.226   <none>        5432/TCP   3m15s
dify-postgresql-primary-hl   ClusterIP   None              <none>        5432/TCP   3m15s
dify-postgresql-read         ClusterIP   192.168.149.137   <none>        5432/TCP   3m15s
dify-postgresql-read-hl      ClusterIP   None              <none>        5432/TCP   3m15s
dify-redis-headless          ClusterIP   None              <none>        6379/TCP   3m15s
dify-redis-master            ClusterIP   192.168.9.227     <none>        6379/TCP   3m15s
dify-redis-replicas          ClusterIP   192.168.103.6     <none>        6379/TCP   3m15s
dify-sandbox                 ClusterIP   192.168.157.225   <none>        8194/TCP   3m15s
dify-web                     ClusterIP   192.168.231.141   <none>        3000/TCP   3m15s
weaviate                     ClusterIP   192.168.58.122    <none>        80/TCP     3m15s
weaviate-headless            ClusterIP   None              <none>        80/TCP     3m15s

**Desktop (please complete the following information):**
 - ubuntu 22.04 
 - Helm version (from helm version) [e.g. v3.12.0]
 - Dify version [e.g. 0.4.0]

**Additional context**

**Comment by zhy1** [comment]
The reason for the exception is because of the following wrong code
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dify-vs
  namespace: dify
spec:
  hosts:
    - rag.myapp
  gateways:
    - istio-system/gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: dify-api.dify.svc.cluster.local
            port:
              number: 5001

    - match:
        - uri:
            prefix: /web
      route:
        - destination:
            host: dify-web.dify.svc.cluster.local
            port:
              number: 3000

    - match:
        - uri:
            prefix: /dbread
      route:
        - destination:
            host: dify-postgresql-read.dify.svc.cluster.local
            port:
              number: 5432

    - match:
        - uri:
            prefix: /weaviate
      route:
        - destination:
            host: weaviate.dify.svc.cluster.local
            port:
              number: 80

    # Default route for root path
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: dify-web.dify.svc.cluster.local
            port:
              number: 3000
```
