### ISSUE TITLE
About externalPostgres and externalS3

### ISSUE THREAD

**Issue by wopincm** [BorisPolonsky/dify-helm#136]
**Environment**
version: 0.23.0-rc1
appVersion: "1.0.0"
**Issue Description**
"When using externalPostgres, the DB_PASSWORD configuration item for PostgreSQL in the Dify ConfigMap is commented out
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-api
data:
  # Startup mode, 'api' starts the API server.
  MODE: api
  ......
  # DB_USERNAME: postgres
  # DB_PASSWORD: 4a61-4f42-4936-baf
  DB_HOST: pg-17.dify
  DB_PORT: "5432"
  DB_DATABASE: dify

  REDIS_HOST: dify-redis-master
  REDIS_PORT: "6379"
  # REDIS_USERNAME: ""
  # REDIS_PASSWORD: "difyai123456"
```
When using externalS3 storage, the PVC (Persistent Volume Claim) cannot be created, but the plugin-daemon still requires mounting the PVC.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-plugin-daemon
spec:
......
        volumeMounts:
        - name: app-data
          mountPath: "/app/storage/cwd"
          subPath:
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: dify
```
**To Reproduce**
values.yaml
```yaml
postgresql:
  enabled: false
externalPostgres:
  enabled: true
  username: "postgres"
  password: "4a61-4f42-4936-baf"
  address: pg-17.dify
externalS3:
  enabled: true
  endpoint: "http://minio:9000"
  accessKey: "admin"
  secretKey: "TQEidkY9Mp"
```

**Expected behavior**
Dify needs to know the PostgreSQL password to connect to the database. 
The plugin-daemon needs to create the PVC to mount it, or alternatively, not mount the PVC and store data in S3 instead."
