### ISSUE TITLE
Unstructured deployment question

### ISSUE THREAD

**Issue by nicologiammaria** [BorisPolonsky/dify-helm#184]
Is there a way to use unstructured locally in this chart version? Or should I create a new deployment?
Thanks in advance

**Comment by BorisPolonsky** [comment]
We couldn't quite understand this question. Could you elaborate.

**Comment by nicologiammaria** [comment]
My bad I was unclear.
I am just switching from Dify docker version to Kubernetes and I would like to use something like the unstructured container available in the docker version.
In the docker-compose there is this optional container

```
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    profiles:
      - unstructured
    restart: always
    volumes:
      - ./volumes/unstructured:/app/data
```

My best understanding of Dify right now is that setting up the following environment variables

```
ETL_TYPE=Unstructured 

# Unstructured API path and API key, needs to be configured when ETL_TYPE is Unstructured
# Or using Unstructured for document extractor node for pptx.
# For example: http://unstructured:8000/general/v0/general
UNSTRUCTURED_API_URL=http://unstructured:8000/general/v0/general
UNSTRUCTURED_API_KEY=yourapikey
SCARF_NO_ANALYTICS=true
```

I can connect to a local version of https://unstructured.io/, to expand data preprocessing before chunking.
**Is there already a way to replicate this behavior in the current helm chart that I am missing?**
**Or should I create my own deployment in Kubernetes mirroring the "unstructured" service defined in the docker-compose?**
If I correctly understand the helm charts, it should already work just with the web version.
I think if I try to set somewhere in the environment variables of yuor api-deployment or api-config 

```
UNSTRUCTURED_API_URL={unstructured web endpoint}
UNSTRUCTURED_API_KEY={my api key obtained from the unstructured website}
```
Is that right? (I still didn't manage to make it work properly)
