### ISSUE TITLE
安装本地插件，提示413 Request Entity Too Large

### ISSUE THREAD

**Issue by huiwooo** [BorisPolonsky/dify-helm#204]
环境：kubesphere，内网

操作：
1、使用repacking工具打包offline版本的插件
2、上传本地插件

上传插件时，提示413 Request Entity Too Large

采取的部分措施：
1、已修改client_max_body_size 500m;

官方issue说是还要修改UPLOAD_FILE_SIZE_LIMIT，请问这个在哪里修改或者在哪里配置？或者是这个上传问题应该如何才能解决？

**Comment by BorisPolonsky** [comment]
https://github.com/BorisPolonsky/dify-helm/tree/master/charts/dify#environment-variables

**Comment by huiwooo** [comment]
我调整了dify-api的yaml文件，变更成如下：

![Image](https://github.com/user-attachments/assets/2a413c2c-ae1a-4bb3-a4c4-2e39c2c3b040)

然而我在上传本地插件时，依旧显示错误，而根据官方的指导手册，是需要添加FORCE_VERIFYING_SIGNATURE为false

![Image](https://github.com/user-attachments/assets/0510fa22-81e1-4a99-9b6c-cde48d90af07)


请问是我填写的位置不对吗？我该如何调整？

**Comment by BorisPolonsky** [comment]
https://github.com/langgenius/dify-plugin-daemon/blob/1e260eedf4f07b81a47f79228604a88d58b4da2d/internal/types/app/config.go#L136

```yaml
pluginDaemon:
  extraEnv:
  # Apply your own Environment Variables if necessary
  - name: "FORCE_VERIFYING_SIGNATURE"
    value: "false"
```
